action: train # train or test
name: ???
split: train
resume_from: ???

save:
  num_clips: 5
  dense_sampling:
    RGB: True
    EMG: True
  num_frames_per_clip:
    RGB: 16
    EMG: 32

dataset:
  annotations_path: ../drive/MyDrive/train_val_EMG
  shift: ActionNet-ActionNet
  workers: 4
  stride: 2
  resolution: 224
  
# these are the action recognition models for each modality
models:
  EMG:
    model: ImgVAE
    dropout: 0.5
    normalize: False
    resolution: 224
    kwargs: {}
    lr_steps: 50 
    epochs: 100
    lr: 1e-6
    sgd_momentum: 0.9
    weight_decay: 1e-7
    weight_i3d_rgb: './pretrained_i3d/rgb_imagenet.pt'


